// apps/web/components/VaultInteraction.tsx
"use client";

import { useState, type ChangeEvent } from "react";
import { useWallet } from "./providers/WalletProvider";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "./ui/card";
import { Button } from "./ui/button";
import { Input } from "./ui/input";
import { Label } from "./ui/label";
import { Alert, AlertDescription, AlertTitle } from "./ui/alert";
import { CheckCircle2, XCircle, Info } from "lucide-react";
import type { TransactionResult, VaultTransaction } from "../lib/transactions";

export function VaultInteraction() {
  const { walletManager, signAndSubmit, isConnected, addEvent, showStatus } = useWallet();
  const [vaultId, setVaultId] = useState("");
  const [amount, setAmount] = useState("");
  const [action, setAction] = useState<"deposit" | "withdraw">("deposit");
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [result, setResult] = useState<TransactionResult | null>(null);

  const handleSubmit = async () => {
    if (!walletManager || !walletManager.account) {
      showStatus("Please connect a wallet first", "error");
      return;
    }

    if (!vaultId || !amount) {
      showStatus("Please provide vault ID and amount", "error");
      return;
    }

    const parsedAmount = Number(amount);
    if (!Number.isInteger(parsedAmount) || parsedAmount <= 0) {
      showStatus("Amount must be a positive integer (drops)", "error");
      return;
    }

    try {
      setIsSubmitting(true);
      setResult(null);

      const transaction: VaultTransaction = {
        TransactionType: action === "deposit" ? "VaultDeposit" : "VaultWithdraw",
        Account: walletManager.account.address,
        VaultID: vaultId,
        Amount: String(parsedAmount),
        ComputationAllowance: 1000000,
        Fee: "1000000",
      };

      const txResult = await signAndSubmit(transaction);

      setResult({
        success: true,
        hash: txResult.hash || "Pending",
        id: txResult.id,
      });

      showStatus(`Vault ${action} successful!`, "success");
      addEvent(`Vault ${action}`, txResult);
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      setResult({
        success: false,
        error: message,
      });
      showStatus(`Vault ${action} failed: ${message}`, "error");
      addEvent(`Vault ${action} Failed`, error);
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <Card>
      <CardHeader className="pb-3">
        <CardTitle className="text-base">Vault Interaction</CardTitle>
        <CardDescription>Deposit and withdraw from smart vaults</CardDescription>
      </CardHeader>

      <CardContent className="space-y-4">
        <div className="space-y-2">
          <Label htmlFor="vaultId">Vault ID</Label>
          <Input
            id="vaultId"
            type="text"
            value={vaultId}
            onChange={(e: ChangeEvent<HTMLInputElement>) => setVaultId(e.target.value)}
            placeholder="Vault ledger ID..."
          />
        </div>

        <div className="space-y-2">
          <Label>Action</Label>
          <div className="flex gap-2">
            <Button
              variant={action === "deposit" ? "default" : "outline"}
              size="sm"
              onClick={() => setAction("deposit")}
            >
              Deposit
            </Button>
            <Button
              variant={action === "withdraw" ? "default" : "outline"}
              size="sm"
              onClick={() => setAction("withdraw")}
            >
              Withdraw
            </Button>
          </div>
        </div>

        <div className="space-y-2">
          <Label htmlFor="vaultAmount">Amount (drops)</Label>
          <Input
            id="vaultAmount"
            type="text"
            value={amount}
            onChange={(e: ChangeEvent<HTMLInputElement>) => setAmount(e.target.value)}
            placeholder="e.g., 1000000"
          />
        </div>

        <div className="rounded-md border p-3 text-sm">
          <p className="font-medium mb-2">Smart Vault Entry Points</p>
          <ul className="text-muted-foreground space-y-1 text-xs">
            <li>on_deposit() - Called when assets are deposited</li>
            <li>on_withdraw() - Called when assets are withdrawn</li>
          </ul>
        </div>

        {isConnected && (
          <Button onClick={handleSubmit} disabled={isSubmitting} className="w-full">
            {isSubmitting ? "Submitting..." : `${action === "deposit" ? "Deposit" : "Withdraw"}`}
          </Button>
        )}

        {!isConnected && (
          <Alert>
            <Info className="h-4 w-4" />
            <AlertDescription>Connect your wallet to interact with vaults</AlertDescription>
          </Alert>
        )}

        {result && (
          <Alert variant={result.success ? "success" : "destructive"}>
            {result.success ? (
              <CheckCircle2 className="h-4 w-4" />
            ) : (
              <XCircle className="h-4 w-4" />
            )}
            <AlertTitle>{result.success ? "Transaction Sent" : "Transaction Failed"}</AlertTitle>
            <AlertDescription>
              {result.success ? (
                <div className="space-y-1">
                  <p className="font-mono text-xs break-all">Hash: {result.hash}</p>
                  {result.id && <p className="text-xs">ID: {result.id}</p>}
                </div>
              ) : (
                <p>{result.error}</p>
              )}
            </AlertDescription>
          </Alert>
        )}
      </CardContent>
    </Card>
  );
}

// apps/web-nuxt/components/VaultInteraction.vue
<script setup lang="ts">
import type { WalletManager } from 'xrpl-connect'

const { walletManager, isConnected, addEvent, showStatus } = useWallet()

const vaultId = ref('')
const amount = ref('')
const action = ref<'deposit' | 'withdraw'>('deposit')
const isSubmitting = ref(false)
const result = ref<{
  success: boolean
  hash?: string
  id?: string
  error?: string
} | null>(null)

const handleSubmit = async () => {
  if (!walletManager.value || !walletManager.value.account) {
    showStatus('Please connect a wallet first', 'error')
    return
  }

  if (!vaultId.value || !amount.value) {
    showStatus('Please provide vault ID and amount', 'error')
    return
  }

  const parsedAmount = Number(amount.value)
  if (!Number.isInteger(parsedAmount) || parsedAmount <= 0) {
    showStatus('Amount must be a positive integer (drops)', 'error')
    return
  }

  try {
    isSubmitting.value = true
    result.value = null

    const transaction: Record<string, unknown> = {
      TransactionType: action.value === 'deposit' ? 'VaultDeposit' : 'VaultWithdraw',
      Account: walletManager.value.account.address,
      VaultID: vaultId.value,
      Amount: String(parsedAmount),
      ComputationAllowance: 1000000,
      Fee: '1000000',
    }

    const txResult = await walletManager.value.signAndSubmit(
      transaction as unknown as Parameters<WalletManager['signAndSubmit']>[0],
    )

    result.value = {
      success: true,
      hash: txResult.hash || 'Pending',
      id: txResult.id,
    }

    showStatus(`Vault ${action.value} successful!`, 'success')
    addEvent(`Vault ${action.value}`, txResult)
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : String(error)
    result.value = {
      success: false,
      error: message,
    }
    showStatus(`Vault ${action.value} failed: ${message}`, 'error')
    addEvent(`Vault ${action.value} Failed`, error)
  } finally {
    isSubmitting.value = false
  }
}
</script>

<template>
  <div class="rounded-lg border bg-card text-card-foreground shadow-sm">
    <div class="p-6 pb-3">
      <h3 class="text-base font-semibold leading-none tracking-tight">Vault Interaction</h3>
      <p class="text-sm text-muted-foreground">Deposit and withdraw from smart vaults</p>
    </div>

    <div class="p-6 pt-0 space-y-4">
      <div class="space-y-2">
        <label for="vaultId" class="text-sm font-medium leading-none">Vault ID</label>
        <input
          id="vaultId"
          v-model="vaultId"
          type="text"
          placeholder="Vault ledger ID..."
          class="flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm transition-colors placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
        />
      </div>

      <div class="space-y-2">
        <label class="text-sm font-medium leading-none">Action</label>
        <div class="flex gap-2">
          <button
            @click="action = 'deposit'"
            :class="[
              'inline-flex items-center justify-center rounded-md text-sm font-medium h-8 px-3',
              action === 'deposit'
                ? 'bg-primary text-primary-foreground shadow hover:bg-primary/90'
                : 'border border-input bg-background hover:bg-accent hover:text-accent-foreground'
            ]"
          >
            Deposit
          </button>
          <button
            @click="action = 'withdraw'"
            :class="[
              'inline-flex items-center justify-center rounded-md text-sm font-medium h-8 px-3',
              action === 'withdraw'
                ? 'bg-primary text-primary-foreground shadow hover:bg-primary/90'
                : 'border border-input bg-background hover:bg-accent hover:text-accent-foreground'
            ]"
          >
            Withdraw
          </button>
        </div>
      </div>

      <div class="space-y-2">
        <label for="vaultAmount" class="text-sm font-medium leading-none">Amount (drops)</label>
        <input
          id="vaultAmount"
          v-model="amount"
          type="text"
          placeholder="e.g., 1000000"
          class="flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm transition-colors placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
        />
      </div>

      <div class="rounded-md border p-3 text-sm">
        <p class="font-medium mb-2">Smart Vault Entry Points</p>
        <ul class="text-muted-foreground space-y-1 text-xs">
          <li>on_deposit() - Called when assets are deposited</li>
          <li>on_withdraw() - Called when assets are withdrawn</li>
        </ul>
      </div>

      <button
        v-if="isConnected"
        @click="handleSubmit"
        :disabled="isSubmitting"
        class="inline-flex w-full items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow hover:bg-primary/90 disabled:pointer-events-none disabled:opacity-50"
      >
        {{ isSubmitting ? 'Submitting...' : (action === 'deposit' ? 'Deposit' : 'Withdraw') }}
      </button>

      <div
        v-if="!isConnected"
        class="rounded-lg border p-4"
      >
        <p class="text-sm text-muted-foreground">Connect your wallet to interact with vaults</p>
      </div>

      <div
        v-if="result"
        :class="[
          'rounded-lg border p-4',
          result.success
            ? 'border-emerald-200 bg-emerald-50 text-emerald-800'
            : 'border-destructive/50 bg-destructive/10 text-destructive'
        ]"
      >
        <template v-if="result.success">
          <h4 class="mb-1 font-medium">Transaction Sent</h4>
          <p class="font-mono text-xs break-all">Hash: {{ result.hash }}</p>
          <p v-if="result.id" class="text-xs mt-1">ID: {{ result.id }}</p>
        </template>
        <template v-else>
          <h4 class="mb-1 font-medium">Transaction Failed</h4>
          <p class="text-sm">{{ result.error }}</p>
        </template>
      </div>
    </div>
  </div>
</template>
