// apps/web-nuxt/components/ContractInteraction.vue
<script setup lang="ts">
import type { WalletManager } from 'xrpl-connect'

const { walletManager, isConnected, addEvent, showStatus } = useWallet()

const contractAddress = ref('')
const functionName = ref('')
const functionArgs = ref('')
const isCalling = ref(false)
const callResult = ref<{
  success: boolean
  hash?: string
  id?: string
  error?: string
} | null>(null)

const stringToHex = (str: string) => {
  return Array.from(new TextEncoder().encode(str))
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('')
    .toUpperCase()
}

const loadCounterExample = () => {
  functionName.value = 'increment'
  functionArgs.value = ''
  callResult.value = null
}

const handleCallContract = async () => {
  if (!walletManager.value || !walletManager.value.account) {
    showStatus('Please connect a wallet first', 'error')
    return
  }

  if (!contractAddress.value || !functionName.value) {
    showStatus('Please provide contract address and function name', 'error')
    return
  }

  try {
    isCalling.value = true
    callResult.value = null

    const transaction: Record<string, unknown> = {
      TransactionType: 'ContractCall',
      Account: walletManager.value.account.address,
      ContractAccount: contractAddress.value,
      Fee: '1000000', // 1 XRP in drops
      FunctionName: stringToHex(functionName.value),
      ComputationAllowance: '1000000',
    }

    if (functionArgs.value) {
      transaction.FunctionArguments = stringToHex(functionArgs.value)
    }

    const txResult = await walletManager.value.signAndSubmit(
      transaction as unknown as Parameters<WalletManager['signAndSubmit']>[0],
    )

    callResult.value = {
      success: true,
      hash: txResult.hash || 'Pending',
      id: txResult.id,
    }

    showStatus('Contract called successfully!', 'success')
    addEvent('Contract Called', txResult)
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : String(error)
    callResult.value = {
      success: false,
      error: message,
    }
    showStatus(`Contract call failed: ${message}`, 'error')
    addEvent('Contract Call Failed', error)
  } finally {
    isCalling.value = false
  }
}

const functionNameHex = computed(() => functionName.value ? stringToHex(functionName.value) : '')
const functionArgsHex = computed(() => functionArgs.value ? stringToHex(functionArgs.value) : '')
</script>

<template>
  <div class="rounded-lg border bg-card text-card-foreground shadow-sm">
    <div class="flex items-center justify-between p-6 pb-3">
      <div>
        <h3 class="text-base font-semibold leading-none tracking-tight">Contract Interaction</h3>
        <p class="text-sm text-muted-foreground">Call functions on deployed contracts</p>
      </div>
      <button
        @click="loadCounterExample"
        class="inline-flex items-center justify-center rounded-md text-sm font-medium hover:bg-accent hover:text-accent-foreground h-8 px-3"
      >
        Load Example
      </button>
    </div>

    <div class="p-6 pt-0 space-y-4">
      <div class="space-y-2">
        <label for="contractAddress" class="text-sm font-medium leading-none">
          Contract Address
        </label>
        <input
          id="contractAddress"
          v-model="contractAddress"
          type="text"
          placeholder="rAddress..."
          class="flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm transition-colors placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
        />
      </div>

      <div class="space-y-2">
        <label for="functionName" class="text-sm font-medium leading-none">Function Name</label>
        <input
          id="functionName"
          v-model="functionName"
          type="text"
          placeholder="e.g., increment, get_value"
          class="flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm transition-colors placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
        />
        <p v-if="functionName" class="text-xs text-muted-foreground">
          Hex: {{ functionNameHex }}
        </p>
      </div>

      <div class="space-y-2">
        <label for="functionArgs" class="text-sm font-medium leading-none">
          Arguments (optional)
        </label>
        <input
          id="functionArgs"
          v-model="functionArgs"
          type="text"
          placeholder="e.g., 5, hello"
          class="flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm transition-colors placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
        />
        <p v-if="functionArgs" class="text-xs text-muted-foreground">
          Hex: {{ functionArgsHex }}
        </p>
      </div>

      <div class="rounded-md border p-3 text-sm">
        <p class="font-medium mb-2">Counter Contract Functions</p>
        <ul class="text-muted-foreground space-y-1 text-xs">
          <li>increment - Increase counter by 1</li>
          <li>decrement - Decrease counter by 1</li>
          <li>get_value - Get current counter value</li>
          <li>reset - Reset counter to 0</li>
        </ul>
      </div>

      <button
        v-if="isConnected && contractAddress && functionName"
        @click="handleCallContract"
        :disabled="isCalling"
        class="inline-flex w-full items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow hover:bg-primary/90 disabled:pointer-events-none disabled:opacity-50"
      >
        {{ isCalling ? 'Calling Contract...' : 'Call Contract' }}
      </button>

      <div
        v-if="!isConnected"
        class="rounded-lg border p-4"
      >
        <p class="text-sm text-muted-foreground">Connect your wallet to interact with contracts</p>
      </div>

      <div
        v-if="callResult"
        :class="[
          'rounded-lg border p-4',
          callResult.success
            ? 'border-emerald-200 bg-emerald-50 text-emerald-800'
            : 'border-destructive/50 bg-destructive/10 text-destructive'
        ]"
      >
        <template v-if="callResult.success">
          <h4 class="mb-1 font-medium">Contract Called</h4>
          <p class="font-mono text-xs break-all">Hash: {{ callResult.hash }}</p>
          <p v-if="callResult.id" class="text-xs mt-1">ID: {{ callResult.id }}</p>
        </template>
        <template v-else>
          <h4 class="mb-1 font-medium">Call Failed</h4>
          <p class="text-sm">{{ callResult.error }}</p>
        </template>
      </div>
    </div>
  </div>
</template>

// apps/web/components/ContractInteraction.tsx
"use client";

import { useState, type ChangeEvent } from "react";
import { useWallet } from "./providers/WalletProvider";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "./ui/card";
import { Button } from "./ui/button";
import { Input } from "./ui/input";
import { Label } from "./ui/label";
import { Alert, AlertDescription, AlertTitle } from "./ui/alert";
import { CheckCircle2, XCircle, Info } from "lucide-react";
import { stringToHex } from "../lib/utils";
import type { ContractCallTransaction, TransactionResult } from "../lib/transactions";

export function ContractInteraction() {
  const { walletManager, signAndSubmit, isConnected, addEvent, showStatus } = useWallet();
  const [contractAddress, setContractAddress] = useState("");
  const [functionName, setFunctionName] = useState("");
  const [functionArgs, setFunctionArgs] = useState("");
  const [isCalling, setIsCalling] = useState(false);
  const [callResult, setCallResult] = useState<TransactionResult | null>(null);

  const loadCounterExample = () => {
    setFunctionName("increment");
    setFunctionArgs("");
    setCallResult(null);
  };

  const handleCallContract = async () => {
    if (!walletManager || !walletManager.account) {
      showStatus("Please connect a wallet first", "error");
      return;
    }

    if (!contractAddress || !functionName) {
      showStatus("Please provide contract address and function name", "error");
      return;
    }

    try {
      setIsCalling(true);
      setCallResult(null);

      const transaction: ContractCallTransaction = {
        TransactionType: "ContractCall",
        Account: walletManager.account.address,
        ContractAccount: contractAddress,
        Fee: "1000000", // 1 XRP in drops
        FunctionName: stringToHex(functionName),
        ComputationAllowance: "1000000",
      };

      if (functionArgs) {
        transaction.FunctionArguments = stringToHex(functionArgs);
      }

      const txResult = await signAndSubmit(transaction);

      setCallResult({
        success: true,
        hash: txResult.hash || "Pending",
        id: txResult.id,
      });

      showStatus("Contract called successfully!", "success");
      addEvent("Contract Called", txResult);
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      setCallResult({
        success: false,
        error: message,
      });
      showStatus(`Contract call failed: ${message}`, "error");
      addEvent("Contract Call Failed", error);
    } finally {
      setIsCalling(false);
    }
  };

  return (
    <Card>
      <CardHeader className="pb-3">
        <div className="flex items-center justify-between">
          <div>
            <CardTitle className="text-base">Contract Interaction</CardTitle>
            <CardDescription>Call functions on deployed contracts</CardDescription>
          </div>
          <Button variant="ghost" size="sm" onClick={loadCounterExample}>
            Load Example
          </Button>
        </div>
      </CardHeader>

      <CardContent className="space-y-4">
        <div className="space-y-2">
          <Label htmlFor="contractAddress">Contract Address</Label>
          <Input
            id="contractAddress"
            type="text"
            value={contractAddress}
            onChange={(e: ChangeEvent<HTMLInputElement>) => setContractAddress(e.target.value)}
            placeholder="rAddress..."
          />
        </div>

        <div className="space-y-2">
          <Label htmlFor="functionName">Function Name</Label>
          <Input
            id="functionName"
            type="text"
            value={functionName}
            onChange={(e: ChangeEvent<HTMLInputElement>) => setFunctionName(e.target.value)}
            placeholder="e.g., increment, get_value"
          />
          {functionName && (
            <p className="text-xs text-muted-foreground">Hex: {stringToHex(functionName)}</p>
          )}
        </div>

        <div className="space-y-2">
          <Label htmlFor="functionArgs">Arguments (optional)</Label>
          <Input
            id="functionArgs"
            type="text"
            value={functionArgs}
            onChange={(e: ChangeEvent<HTMLInputElement>) => setFunctionArgs(e.target.value)}
            placeholder="e.g., 5, hello"
          />
          {functionArgs && (
            <p className="text-xs text-muted-foreground">Hex: {stringToHex(functionArgs)}</p>
          )}
        </div>

        <div className="rounded-md border p-3 text-sm">
          <p className="font-medium mb-2">Counter Contract Functions</p>
          <ul className="text-muted-foreground space-y-1 text-xs">
            <li>increment - Increase counter by 1</li>
            <li>decrement - Decrease counter by 1</li>
            <li>get_value - Get current counter value</li>
            <li>reset - Reset counter to 0</li>
          </ul>
        </div>

        {isConnected && contractAddress && functionName && (
          <Button onClick={handleCallContract} disabled={isCalling} className="w-full">
            {isCalling ? "Calling Contract..." : "Call Contract"}
          </Button>
        )}

        {!isConnected && (
          <Alert>
            <Info className="h-4 w-4" />
            <AlertDescription>Connect your wallet to interact with contracts</AlertDescription>
          </Alert>
        )}

        {callResult && (
          <Alert variant={callResult.success ? "success" : "destructive"}>
            {callResult.success ? (
              <CheckCircle2 className="h-4 w-4" />
            ) : (
              <XCircle className="h-4 w-4" />
            )}
            <AlertTitle>{callResult.success ? "Contract Called" : "Call Failed"}</AlertTitle>
            <AlertDescription>
              {callResult.success ? (
                <div className="space-y-1">
                  <p className="font-mono text-xs break-all">Hash: {callResult.hash}</p>
                  {callResult.id && <p className="text-xs">ID: {callResult.id}</p>}
                </div>
              ) : (
                <p>{callResult.error}</p>
              )}
            </AlertDescription>
          </Alert>
        )}
      </CardContent>
    </Card>
  );
}
