// apps/web-nuxt/components/TransactionForm.vue
<script setup lang="ts">
import {
  useSigner,
  useWallet as useBindingWallet,
} from '@xrpl-commons/xrpl-connect-vue'
import { isWalletError, WalletErrorCode } from 'xrpl-connect'
import { isValidClassicAddress } from 'xrpl'
import { buildPaymentTransaction, normalizeSubmittedPaymentResult } from '~/lib/payment.mjs'

type PaymentResult =
  | {
      status: 'submitted' | 'validated'
      hash: string
      id?: string
      resultCode?: string
    }
  | {
      status: 'cancelled' | 'error'
      hash?: string
      id?: string
      resultCode?: string
      error: string
    }

const { connected, account, connecting } = useBindingWallet()
const { signAndSubmit } = useSigner()
const { selectedNetwork, addEvent, showStatus } = useWallet()

const destination = ref('')
const amountXrp = ref('')
const destinationTag = ref('')
const result = ref<PaymentResult | null>(null)
const isSubmitting = ref(false)

const networkMismatch = computed(
  () => Boolean(account.value && account.value.network.id !== selectedNetwork.value.id),
)
const failureMessage = computed(() =>
  result.value && 'error' in result.value ? result.value.error : null,
)
const paymentCancelled = computed(() => result.value?.status === 'cancelled')

function getErrorMessage(error: unknown) {
  return error instanceof Error ? error.message : String(error)
}

function isCancelledWalletAction(error: unknown) {
  return (
    isWalletError(error) &&
    [WalletErrorCode.SIGN_REJECTED, WalletErrorCode.CONNECTION_REJECTED].includes(error.code)
  )
}

async function handleSubmit() {
  if (isSubmitting.value) return

  if (!connected.value || !account.value) {
    showStatus('Connect a wallet before sending XRP.', 'error')
    return
  }

  isSubmitting.value = true
  result.value = null

  try {
    const transaction = buildPaymentTransaction({
      accountAddress: account.value.address,
      accountNetworkId: account.value.network.id,
      selectedNetworkId: selectedNetwork.value.id,
      destination: destination.value,
      amountXrp: amountXrp.value,
      destinationTag: destinationTag.value,
      isValidAddress: isValidClassicAddress,
    })
    const submittedTransaction = await signAndSubmit(
      transaction as Parameters<typeof signAndSubmit>[0],
    )
    const nextResult = normalizeSubmittedPaymentResult(submittedTransaction) as PaymentResult

    if (nextResult.status === 'error') {
      result.value = nextResult
      showStatus(`Payment failed: ${nextResult.error}`, 'error')
      addEvent('Payment Failed', nextResult)
      return
    }

    result.value = nextResult
    showStatus(
      nextResult.status === 'validated'
        ? 'Payment validated on the ledger.'
        : 'Payment submitted; validation is pending.',
      'success',
    )
    addEvent('Payment Submitted', submittedTransaction)
    destination.value = ''
    amountXrp.value = ''
    destinationTag.value = ''
  } catch (error) {
    const cancelled = isCancelledWalletAction(error)
    const message = cancelled ? 'Transaction signing was cancelled.' : getErrorMessage(error)
    result.value = { status: cancelled ? 'cancelled' : 'error', error: message }

    if (cancelled) {
      showStatus(message, 'info')
    } else {
      showStatus(`Payment failed: ${message}`, 'error')
      addEvent('Payment Failed', error)
    }
  } finally {
    isSubmitting.value = false
  }
}
</script>

<template>
  <section class="min-w-0 rounded-xl border bg-card p-6 text-card-foreground shadow-sm md:p-8">
    <div class="space-y-1">
      <h2 class="text-xl font-semibold tracking-tight">Send XRP</h2>
      <p class="text-sm text-muted-foreground">Send XRP on {{ selectedNetwork.name }}.</p>
    </div>

    <div class="mt-6">
      <div
        v-if="networkMismatch"
        role="alert"
        class="mb-5 rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"
      >
        Your wallet is on {{ account?.network.name }}. Switch it to {{ selectedNetwork.name }}
        before sending.
      </div>

      <form class="space-y-6" @submit.prevent="handleSubmit">
        <div class="space-y-2">
          <label for="destination" class="text-sm font-medium leading-none">
            Destination address
          </label>
          <input
            id="destination"
            v-model="destination"
            :disabled="isSubmitting"
            type="text"
            autocomplete="off"
            placeholder="r…"
            class="flex h-12 w-full rounded-lg border border-input bg-transparent px-3 py-1 text-base shadow-sm transition-colors placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
            required
          >
        </div>

        <div class="space-y-2">
          <label for="amountXrp" class="text-sm font-medium leading-none">Amount (XRP)</label>
          <div class="relative">
            <input
              id="amountXrp"
              v-model="amountXrp"
              :disabled="isSubmitting"
              type="text"
              inputmode="decimal"
              autocomplete="off"
              placeholder="1.5"
              aria-describedby="amount-help"
              class="flex h-12 w-full rounded-lg border border-input bg-transparent px-3 py-1 pr-16 text-base shadow-sm transition-colors placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
              required
            >
            <span
              aria-hidden="true"
              class="pointer-events-none absolute inset-y-0 right-4 flex items-center text-sm text-muted-foreground"
            >
              XRP
            </span>
          </div>
          <p id="amount-help" class="text-xs text-muted-foreground">Up to six decimal places.</p>
        </div>

        <details class="group">
          <summary
            class="flex cursor-pointer list-none items-center gap-2 text-sm font-medium focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring [&::-webkit-details-marker]:hidden"
          >
            <svg
              aria-hidden="true"
              class="h-4 w-4 shrink-0 transition-transform group-open:rotate-180"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
            >
              <path stroke-linecap="round" stroke-linejoin="round" d="m6 9 6 6 6-6" />
            </svg>
            <span v-if="destinationTag.trim()">
              Destination tag: {{ destinationTag.trim() }}
            </span>
            <template v-else>
              <span>Add destination tag</span>
              <span class="font-normal text-muted-foreground">(optional)</span>
            </template>
          </summary>
          <div class="mt-4 space-y-2">
            <label for="destinationTag" class="text-sm font-medium leading-none">
              Destination tag
            </label>
            <input
              id="destinationTag"
              v-model="destinationTag"
              :disabled="isSubmitting"
              aria-describedby="destination-tag-help"
              type="text"
              inputmode="numeric"
              autocomplete="off"
              placeholder="e.g. 12345"
              class="flex h-12 w-full rounded-lg border border-input bg-transparent px-3 py-1 text-base shadow-sm transition-colors placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
            >
            <p id="destination-tag-help" class="text-xs text-muted-foreground">
              Include the tag if the recipient requires one.
            </p>
          </div>
        </details>

        <button
          type="submit"
          :disabled="!connected || connecting || networkMismatch || isSubmitting"
          class="inline-flex h-12 w-full items-center justify-center rounded-lg bg-primary px-4 text-sm font-medium text-primary-foreground shadow hover:bg-primary/90 disabled:pointer-events-none disabled:bg-muted disabled:text-muted-foreground disabled:shadow-none"
        >
          {{ isSubmitting ? 'Waiting for wallet…' : 'Sign & submit payment' }}
        </button>
      </form>

      <div
        v-if="result?.status === 'submitted' || result?.status === 'validated'"
        role="status"
        aria-live="polite"
        class="mt-4 rounded-lg border border-emerald-200 bg-emerald-50 p-4 text-emerald-800"
      >
        <h3 class="mb-1 font-medium">
          {{ result.status === 'validated' ? 'Payment validated' : 'Payment submitted' }}
        </h3>
        <p class="break-all font-mono text-xs">Hash: {{ result.hash }}</p>
        <p v-if="result.id" class="mt-1 text-xs">ID: {{ result.id }}</p>
        <p v-if="result.status === 'submitted'" class="mt-1 text-xs">
          The ledger has not reported validation yet.
        </p>
      </div>

      <div
        v-else-if="failureMessage"
        role="alert"
        :class="[
          'mt-4 rounded-lg border p-4',
          paymentCancelled
            ? 'border-amber-200 bg-amber-50 text-amber-900'
            : 'border-destructive/50 bg-destructive/10 text-destructive',
        ]"
      >
        <h3 class="mb-1 font-medium">
          {{ paymentCancelled ? 'Payment cancelled' : 'Payment failed' }}
        </h3>
        <p class="text-sm">{{ failureMessage }}</p>
      </div>
    </div>
  </section>
</template>

// apps/web/components/TransactionForm.tsx
"use client";

import { useRef, useState, type FormEvent } from "react";
import { useSigner, useWallet as useBindingWallet } from "@xrpl-commons/xrpl-connect-react";
import { isWalletError, WalletErrorCode } from "xrpl-connect";
import { isValidClassicAddress } from "xrpl";
import { useWallet } from "./providers/WalletProvider";
import { buildPaymentTransaction, normalizeSubmittedPaymentResult } from "../lib/payment";
import type { NormalizedPaymentResult } from "../lib/payment";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "./ui/card";
import { Button } from "./ui/button";
import { Input } from "./ui/input";
import { Label } from "./ui/label";
import { Alert, AlertDescription, AlertTitle } from "./ui/alert";
import { CheckCircle2, ChevronDown, XCircle } from "lucide-react";

type PaymentFormResult =
  | NormalizedPaymentResult
  | {
      status: "cancelled";
      error: string;
    };

function getErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

function isCancelledWalletAction(error: unknown): boolean {
  return (
    isWalletError(error) &&
    [WalletErrorCode.SIGN_REJECTED, WalletErrorCode.CONNECTION_REJECTED].includes(error.code)
  );
}

export function TransactionForm() {
  const { connected, account, connecting } = useBindingWallet();
  const { signAndSubmit } = useSigner();
  const { selectedNetwork, addEvent, showStatus } = useWallet();
  const [destination, setDestination] = useState("");
  const [amountXrp, setAmountXrp] = useState("");
  const [destinationTag, setDestinationTag] = useState("");
  const [result, setResult] = useState<PaymentFormResult | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const submittingRef = useRef(false);

  const networkMismatch = Boolean(account && account.network.id !== selectedNetwork.id);

  const handleSubmit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (submittingRef.current || isSubmitting) return;

    if (!connected || !account) {
      showStatus("Connect a wallet before sending XRP.", "error");
      return;
    }

    submittingRef.current = true;
    setIsSubmitting(true);
    setResult(null);

    try {
      const transaction = buildPaymentTransaction({
        accountAddress: account.address,
        accountNetworkId: account.network.id,
        selectedNetworkId: selectedNetwork.id,
        destination,
        amountXrp,
        destinationTag,
        isValidAddress: isValidClassicAddress,
      });
      const submittedTransaction = await signAndSubmit(transaction);
      const nextResult = normalizeSubmittedPaymentResult(submittedTransaction);

      if (nextResult.status === "error") {
        setResult(nextResult);
        showStatus(`Payment failed: ${nextResult.error}`, "error");
        addEvent("Payment Failed", submittedTransaction);
        return;
      }

      setResult(nextResult);
      showStatus(
        nextResult.status === "validated"
          ? "Payment validated on the ledger."
          : "Payment submitted; validation is pending.",
        "success"
      );
      addEvent("Payment Submitted", submittedTransaction);
      setDestination("");
      setAmountXrp("");
      setDestinationTag("");
    } catch (error) {
      const cancelled = isCancelledWalletAction(error);
      const message = cancelled ? "Transaction signing was cancelled." : getErrorMessage(error);
      setResult({ status: cancelled ? "cancelled" : "error", error: message });
      if (cancelled) {
        showStatus(message, "info");
      } else {
        showStatus(`Payment failed: ${message}`, "error");
        addEvent("Payment Failed", error);
      }
    } finally {
      submittingRef.current = false;
      setIsSubmitting(false);
    }
  };

  return (
    <Card className="min-w-0 rounded-xl">
      <CardHeader className="p-6 pb-6 md:p-8 md:pb-6">
        <CardTitle className="text-xl">Send XRP</CardTitle>
        <CardDescription>Send XRP on {selectedNetwork.name}.</CardDescription>
      </CardHeader>

      <CardContent className="p-6 pt-0 md:p-8 md:pt-0">
        <form onSubmit={handleSubmit} className="space-y-6">
          <div className="space-y-2">
            <Label htmlFor="destination">Destination address</Label>
            <Input
              id="destination"
              type="text"
              autoComplete="off"
              placeholder="r…"
              className="h-12 rounded-lg text-base"
              disabled={isSubmitting}
              value={destination}
              onChange={(event) => setDestination(event.target.value)}
              required
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="amountXrp">Amount (XRP)</Label>
            <div className="relative">
              <Input
                id="amountXrp"
                type="text"
                inputMode="decimal"
                autoComplete="off"
                placeholder="1.5"
                className="h-12 rounded-lg pr-16 text-base"
                value={amountXrp}
                onChange={(event) => setAmountXrp(event.target.value)}
                aria-describedby="amount-help"
                disabled={isSubmitting}
                required
              />
              <span
                aria-hidden="true"
                className="pointer-events-none absolute inset-y-0 right-4 flex items-center text-sm text-muted-foreground"
              >
                XRP
              </span>
            </div>
            <p id="amount-help" className="text-xs text-muted-foreground">
              Up to six decimal places.
            </p>
          </div>

          <details className="group">
            <summary className="flex cursor-pointer list-none items-center gap-2 rounded-md text-sm font-medium focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring [&::-webkit-details-marker]:hidden">
              <ChevronDown
                className="h-4 w-4 shrink-0 transition-transform group-open:rotate-180"
                aria-hidden="true"
              />
              {destinationTag.trim() ? `Destination tag: ${destinationTag}` : "Add destination tag"}
              {!destinationTag.trim() && (
                <span className="font-normal text-muted-foreground">(optional)</span>
              )}
            </summary>
            <div className="mt-4 space-y-2">
              <Label htmlFor="destinationTag">Destination tag</Label>
              <Input
                id="destinationTag"
                type="text"
                inputMode="numeric"
                autoComplete="off"
                placeholder="e.g. 12345"
                className="h-12 rounded-lg text-base"
                value={destinationTag}
                onChange={(event) => setDestinationTag(event.target.value)}
                aria-describedby="destination-tag-help"
                disabled={isSubmitting}
              />
              <p id="destination-tag-help" className="text-xs text-muted-foreground">
                Include the tag if the recipient requires one.
              </p>
            </div>
          </details>

          <Button
            type="submit"
            disabled={!connected || connecting || networkMismatch || isSubmitting}
            className="h-12 w-full rounded-lg disabled:bg-muted disabled:text-muted-foreground disabled:opacity-100 disabled:shadow-none"
          >
            {isSubmitting ? "Waiting for wallet…" : "Sign & submit payment"}
          </Button>
        </form>

        {result ? (
          result.status === "submitted" || result.status === "validated" ? (
            <Alert variant="success" className="mt-4" role="status">
              <CheckCircle2 className="h-4 w-4" />
              <AlertTitle>
                {result.status === "validated" ? "Payment validated" : "Payment submitted"}
              </AlertTitle>
              <AlertDescription>
                <div className="space-y-1">
                  <p className="break-all font-mono text-xs">Hash: {result.hash}</p>
                  {result.id && <p className="text-xs">ID: {result.id}</p>}
                  {result.status === "submitted" && (
                    <p className="text-xs">The ledger has not reported validation yet.</p>
                  )}
                </div>
              </AlertDescription>
            </Alert>
          ) : (
            <Alert
              variant={result.status === "cancelled" ? "warning" : "destructive"}
              className="mt-4"
              role="alert"
            >
              <XCircle className="h-4 w-4" />
              <AlertTitle>
                {result.status === "cancelled" ? "Payment cancelled" : "Payment failed"}
              </AlertTitle>
              <AlertDescription>{result.error}</AlertDescription>
            </Alert>
          )
        ) : null}
      </CardContent>
    </Card>
  );
}
