// apps/web-nuxt/components/WalletConnector.vue
<script setup lang="ts">
import { WalletConnector as XrplWalletConnector } from '@xrpl-commons/xrpl-connect-vue'

const { showStatus } = useWallet()

function handleConnecting(walletId: string) {
  showStatus(`Connecting to ${walletId}…`, 'info')
}

function handleConnected() {
  showStatus('Wallet connected', 'success')
}

function handleError(error: { message?: string }) {
  showStatus(error.message || 'Wallet connection failed', 'error')
}
</script>

<template>
  <div class="flex flex-col items-end gap-1">
    <XrplWalletConnector
      id="wallet-connector"
      aria-label="Choose an XRPL wallet"
      primary-wallet="xaman"
      :wallets="['xaman', 'gemwallet', 'walletconnect']"
      show-unavailable
      theme="light"
      :css-vars="{
        '--xc-font-family': 'inherit',
        '--xc-border-radius': '0.5rem',
        '--xc-connect-button-border-radius': '0.375rem',
      }"
      @connecting="handleConnecting"
      @connect="handleConnected"
      @error="handleError"
    />
  </div>
</template>

// apps/web/components/WalletConnector.tsx
"use client";

import dynamic from "next/dynamic";
import { useWallet } from "./providers/WalletProvider";

function WalletConnectorPlaceholder() {
  return (
    <span
      role="status"
      aria-label="Loading wallet connection options"
      aria-live="polite"
      aria-busy="true"
      className="inline-flex h-9 min-w-32 items-center justify-center rounded-md border border-input bg-muted/50 px-3 text-xs text-muted-foreground"
    >
      Loading wallets…
    </span>
  );
}

const XrplWalletConnector = dynamic(
  () => import("@xrpl-commons/xrpl-connect-react").then(({ WalletConnector }) => WalletConnector),
  {
    ssr: false,
    loading: WalletConnectorPlaceholder,
  }
);

export function WalletConnector() {
  const { showStatus } = useWallet();

  return (
    <XrplWalletConnector
      id="wallet-connector"
      aria-label="Choose an XRPL wallet"
      primaryWallet="xaman"
      wallets={["xaman", "gemwallet", "walletconnect"]}
      showUnavailable
      theme="light"
      cssVars={{
        "--xc-font-family": "inherit",
        "--xc-border-radius": "0.5rem",
        "--xc-connect-button-border-radius": "0.375rem",
      }}
      onConnecting={(walletId) => showStatus(`Connecting to ${walletId}…`, "info")}
      onConnect={() => showStatus("Wallet connected", "success")}
      onError={(error) => showStatus(error.message, "error")}
    />
  );
}
